#!/bin/sh
# arch-tag: Debhelper script for Haskell
#
# Bert Massop, 2013. Modified to more eagerly replace directory names, accept
#                    custom Dh_Haskell.sh (which allows to use custom package
#                    DB).
#
# Copyright (C) 2009 Marco Túlio Gontijo e Silva <marcot@debian.org>
# Based on mk-haskell-depends by Martin Sjögren <sjogren@debian.org>
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -e

. debian/scripts/Dh_Haskell.sh

pkgs=`dh_listpackages $args`

for pkg in $pkgs
do
    case "$pkg" in
        libghc-*-dev)
	    if [ -z "$files" ] ; then
		files=`find_config_for_ghc $pkg`
	    fi
            ;;
    esac
done

if [ -z "$files" ]
then
	echo "No installed package description files can not be found" >&2
	exit 1
fi

T_DIR=debian/dh_haskell_shlibdeps
mkdir $T_DIR 2> /dev/null || true
# echo '[]' > $T_DIR/package.conf
for file in $files
do
    pkg=`echo $file | cut -d/ -f2 | cut -d- -f2- | sed -e 's/-[^-]\+$//'`
    pkgconflocal=$T_DIR/$pkg.package.conf
    cat $file | sed -e \
        "s#/usr/lib/haskell-packages#$PWD/debian/libghc-$pkg-dev/usr/lib/haskell-packages#g" \
        > $pkgconflocal
    if [ -n "${pkgdb}" ]
    then
        db=${pkgdb##--package-db=}
        cp $db/*.conf $T_DIR/
        ghc-pkg -f $T_DIR recache
    fi
    ghc-pkg -f $T_DIR register $pkgconflocal --force || true
done
for pkg in $pkgs
do
    case "$pkg" in
        libghc-*-dev)
            sfile=debian/$pkg.substvars
            pkgname=`basename debian/$pkg/usr/lib/haskell-packages/ghc/lib/* | sed -e 's/-[^-]\+$//'`
            touch $sfile
            echo "module Main where main = return ()" > $T_DIR/a.hs
            ghc --make $T_DIR/a.hs -o $T_DIR/a.out -package-conf \
                $T_DIR -package $pkgname
            dpkg-shlibdeps -Tdebian/$pkg.substvars $T_DIR/a.out

	    # remove the dependencies on shared libs already in the ghc package
	    if [ $(nm -u $T_DIR/a.o | grep 'U ffi_' | wc -l) -eq 0 ]; then
		libffi=$(dpkg -s ghc | sed -n '/^Depends/s/.*\(libffi[0-9][0-9]*\).*/\1/p')
		sed -i -r "s/ *$libffi[^,]*"'(, *|$)//g;s/,$//' debian/$pkg.substvars
	    fi
	    if [ $(nm -u $T_DIR/a.o | grep 'U __gmp' | wc -l) -eq 0 ]; then
		libgmp=$(dpkg -s ghc | sed -n '/^Depends/s/.*\(libgmp[0-9][0-9]*\).*/\1/p')
		sed -i -r "s/ *$libgmp[^,]*"'(, *|$)//g;s/,$//' debian/$pkg.substvars
	    fi
            ;;
    esac
done
rm -rf $T_DIR
